name: Publish extension
on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  tag:
    name: Tag Build
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.setup_id.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main

      - name: Versioning
        id: versioning
        uses: paulhatch/semantic-version@v4.0.1
        with:
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          format: "${major}.${minor}.${patch}"
          short_tags: false
          bump_each_commit: false

      - name: Set output
        id: setup_id
        run: |
          VERSION=${{ steps.versioning.outputs.major }}.${{ steps.versioning.outputs.minor }}.${{ steps.versioning.outputs.patch }}
          echo VERSION=$VERSION
          echo "::set-output name=version::$VERSION"

      - name: Tag Build
        continue-on-error: true
        uses: actions/github-script@v6
        with:
          github-token: ${{ github.token }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{steps.setup_id.outputs.version}}",
              sha: context.sha
            })

  release:
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install the dependencies
        run: npm i

      - name: Install vsce
        run: npm i -g vsce

      # - name: Unpublish
      #   run: vsce unpublish artificial.artificial-vscode-extension -p ${{ secrets.AZURE_MARKETPLACE_TOKEN }}

      - name: Publish
        run: vsce publish -p ${{ secrets.AZURE_MARKETPLACE_TOKEN }}
